//
//  Client.swift
//  raccoon
//
//  Created by Manuel García-Estañ on 8/10/16.
//  Copyright © 2016 manuege. All rights reserved.
//

import Foundation
import CoreData
import Alamofire
import AlamofireCoreData
import PromiseKit

/**
 Clients are instances that can send network requests. The requests are built using `Endpoints`.
 The responses of this endpoints will be inserted in the given managed object context.
 */
public protocol Client {
    
    // MARK: Required
    
    /// The base url which will be used to build the reqeusts
    var baseURL: String { get }
    
    /// The managed object context where all the responses will be inserted.
    var context: NSManagedObjectContext { get }
    
    // MARK: Optionals
    /**
     The DataResponseSerializer<Any> which will transform the original response to the JSON which will be used to insert the responses.
     By default it is `DataRequest.jsonResponseSerializer()`
     */
    var jsonSerializer: DataResponseSerializer<Any> { get }
    
    /**
     Use this method to perform any last minute changes on the DataRequest to send.
     Here you can add some validations, log the requests, or whatever thing you need.
     By default, it returns the request itself, without any addition
 
     - parameter request: The request that will be sent
     - parameter endpoint: The endpoint which launched the reqeust
 
     - returns: the modified request
     */
    func prepare(_ request: DataRequest, for endpoint: Endpoint) -> DataRequest
    
    /**
     Use this method to perform any last minute changes on the Promise created when a request is sent.
     Here you can add some common `recover` or `then` to all the promise
     By default, it returns the promise itself, without any addition
 
     - parameter request: The `Promise`
     - parameter endpoint: The `Endpoint` that launched the request
 
     - returns: the modified request
     */
    func process<T>(_ promise: Promise<T>, for endpoint: Endpoint) -> Promise<T>
}

public extension Client {
    
    public var jsonSerializer: DataResponseSerializer<Any> {
        return DataRequest.jsonResponseSerializer()
    }
    
    public func prepare(_ request: DataRequest, for endpoint: Endpoint) -> DataRequest {
        return request
    }
    
    func process<T>(_ promise: Promise<T>, for endpoint: Endpoint) -> Promise<T> {
        return promise
    }
}

public extension Client {
    
    // MARK: - Default methods
    /** 
     Enqueues the request generated by the endpoint and insert it using the generic type.
     It returns a Promise to inform if the request has finished succesfully or not
    
     - parameter endpoint: The endpoint

     - returns: The promise
     */
    public func enqueue<T: Insertable>(_ endpoint: Endpoint) -> Promise<T> {
        
        let promise = Promise<T> { fulfill, reject in
            let request = endpoint.request(withBaseURL: baseURL)
            
            prepare(request, for: endpoint)
                .responseInsert(
                    queue: nil,
                    jsonSerializer: jsonSerializer,
                    context: context,
                    type: T.self) { response in
                        
                        switch response.result {
                        case let .success(value):
                            fulfill(value)
                        case let .failure(error):
                            reject(error)
                        }
            }
        }
        
        return process(promise, for: endpoint)
    }
    
    /** 
     Enqueues the request generated by the endpoint.
     It returns an empty promise to inform if the request has finished succesfully or not
     
     - parameter endpoint: The endpoint
     
     - returns: The promise
     */
    public func enqueue(_ endpoint: Endpoint) -> Promise<Void> {
        
        let promise = Promise<Void> { fulfill, reject in
            let request = endpoint.request(withBaseURL: baseURL)
            
            prepare(request, for: endpoint)
                .responseInsert(
                    jsonSerializer: jsonSerializer,
                    context: context,
                    type: Empty.self) { response in
                        
                        switch response.result {
                        case .success:
                            fulfill()
                        case let .failure(error):
                            reject(error)
                        }
            }
        }
        
        return process(promise, for: endpoint)
    }
}

private struct Empty {}
extension Empty: Insertable {
    public static func insert(from json: Any, in context: NSManagedObjectContext) throws -> Empty {
        return Empty()
    }
}
